version: '3.4'

services:
  movieasy.api:
    image: ${DOCKER_REGISTRY-}movieasyapi
    build:
      context: .
      dockerfile: Movieasy.Api/Dockerfile
    depends_on:
     - postgres
   
  postgres:
    image: postgres
    environment:
    - POSTGRES_DB=movieasy
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    ports:
        - 5432:5432
    volumes:
        - /var/lib/postgresql/data

  movieasy-idp:
    image: jboss/keycloak:latest
    container_name: Movieasy.Identity
    environment:
    - DB_VENDOR=POSTGRES
    - DB_ADDR=postgres
    - DB_DATABASE=movieasy
    - DB_USER=postgres
    - DB_PASSWORD=postgres
    - KEYCLOAK_USER=admin
    - KEYCLOAK_PASSWORD=admin
    - PROXY_ADDRESS_FORWARDING=true
    volumes:
    - ./.containers/identity:/opt/jboss/keycloak/standalone/data
    ports:
    - 18080:8080
    depends_on:
    - postgres
 
